//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18047
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonGate.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoonGate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_036_file {
            get {
                object obj = ResourceManager.GetObject("glyphicons_036_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_149_folder_new {
            get {
                object obj = ResourceManager.GetObject("glyphicons_149_folder_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_232_cloud {
            get {
                object obj = ResourceManager.GetObject("glyphicons_232_cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Failed to Encrypt! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrFailToEncrypt {
            get {
                return ResourceManager.GetString("mesErrFailToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Load Consumer Key! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrFailToLoadId {
            get {
                return ResourceManager.GetString("mesErrFailToLoadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Load Consumer Secret! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrFailToLoadSec {
            get {
                return ResourceManager.GetString("mesErrFailToLoadSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Upload! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrFailToUpload {
            get {
                return ResourceManager.GetString("mesErrFailToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value Mismatching! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrInputMiss {
            get {
                return ResourceManager.GetString("mesErrInputMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is Empty! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesErrValisNull {
            get {
                return ResourceManager.GetString("mesErrValisNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mesExp {
            get {
                return ResourceManager.GetString("mesExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoonGate-{982F430F-AD10-4449-A020-EFC5A5479DA5} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PgId {
            get {
                return ResourceManager.GetString("PgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string titleErr {
            get {
                return ResourceManager.GetString("titleErr", resourceCulture);
            }
        }
    }
}
